export enum PaymentStatus {
  PENDENTE = "PENDENTE",
  PAGO = "PAGO",
  ATRASADO = "ATRASADO",
  CANCELADO = "CANCELADO",
  ISENTO = "ISENTO",
  CONFIRMADO = "CONFIRMADO",
  FALHOU = "FALHOU",
  EM_REPASSE = "EM_REPASSE",
  RECEBIDO = "RECEBIDO",
}
