export const brazilianStates = [
  { id: "AC", value: "AC", label: "Acre" },
  { id: "AL", value: "AL", label: "Alagoas" },
  { id: "AP", value: "AP", label: "Amapá" },
  { id: "AM", value: "AM", label: "Amazonas" },
  { id: "BA", value: "BA", label: "Bahia" },
  { id: "CE", value: "CE", label: "Ceará" },
  { id: "DF", value: "DF", label: "Distrito Federal" },
  { id: "ES", value: "ES", label: "Espírito Santo" },
  { id: "GO", value: "GO", label: "Goiás" },
  { id: "MA", value: "MA", label: "Maranhão" },
  { id: "MT", value: "MT", label: "Mato Grosso" },
  { id: "MS", value: "MS", label: "Mato Grosso do Sul" },
  { id: "MG", value: "MG", label: "Minas Gerais" },
  { id: "PA", value: "PA", label: "Pará" },
  { id: "PB", value: "PB", label: "Paraíba" },
  { id: "PR", value: "PR", label: "Paraná" },
  { id: "PE", value: "PE", label: "Pernambuco" },
  { id: "PI", value: "PI", label: "Piauí" },
  { id: "RJ", value: "RJ", label: "Rio de Janeiro" },
  { id: "RN", value: "RN", label: "Rio Grande do Norte" },
  { id: "RS", value: "RS", label: "Rio Grande do Sul" },
  { id: "RO", value: "RO", label: "Rondônia" },
  { id: "RR", value: "RR", label: "Roraima" },
  { id: "SC", value: "SC", label: "Santa Catarina" },
  { id: "SP", value: "SP", label: "São Paulo" },
  { id: "SE", value: "SE", label: "Sergipe" },
  { id: "TO", value: "TO", label: "Tocantins" },
];
