export const brazilianStates = [
  { id: "AC", value: "Acre", label: "Acre" },
  { id: "AL", value: "Alagoas", label: "Alagoas" },
  { id: "AP", value: "Amapá", label: "Amapá" },
  { id: "AM", value: "Amazonas", label: "Amazonas" },
  { id: "BA", value: "Bahia", label: "Bahia" },
  { id: "CE", value: "Ceará", label: "Ceará" },
  { id: "DF", value: "Distrito Federal", label: "Distrito Federal" },
  { id: "ES", value: "Espírito Santo", label: "Espírito Santo" },
  { id: "GO", value: "Goiás", label: "Goiás" },
  { id: "MA", value: "Maranhão", label: "Maranhão" },
  { id: "MT", value: "Mato Grosso", label: "Mato Grosso" },
  { id: "MS", value: "Mato Grosso do Sul", label: "Mato Grosso do Sul" },
  { id: "MG", value: "Minas Gerais", label: "Minas Gerais" },
  { id: "PA", value: "Pará", label: "Pará" },
  { id: "PB", value: "Paraíba", label: "Paraíba" },
  { id: "PR", value: "Paraná", label: "Paraná" },
  { id: "PE", value: "Pernambuco", label: "Pernambuco" },
  { id: "PI", value: "Piauí", label: "Piauí" },
  { id: "RJ", value: "Rio de Janeiro", label: "Rio de Janeiro" },
  { id: "RN", value: "Rio Grande do Norte", label: "Rio Grande do Norte" },
  { id: "RS", value: "Rio Grande do Sul", label: "Rio Grande do Sul" },
  { id: "RO", value: "Rondônia", label: "Rondônia" },
  { id: "RR", value: "Roraima", label: "Roraima" },
  { id: "SC", value: "Santa Catarina", label: "Santa Catarina" },
  { id: "SP", value: "São Paulo", label: "São Paulo" },
  { id: "SE", value: "Sergipe", label: "Sergipe" },
  { id: "TO", value: "Tocantins", label: "Tocantins" },
];
